version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    # Sin variables de entorno (usará las de tu properties)

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=usuariospa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maia154167681@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: